export const attributeMappings = {
    Grid_id: "Grid ID",
    GN_Uid: "GN UID",
    GND_NO: "GN Division Number",
    PROVINCE_N: "Province Name",
    DISTRICT_N: "District Name",
    DSD_N: "Divisional Secretariat Division",
    GND_N: "GN Division Name",
    Restricted: "Restricted Area",
    Gr_wate: "Ground Water Availability",
    Sta_Hot: "Star Hotels (1-5 Star)",
    Tou_hot: "Tourist Hotels",
    Bou_hot: "Boutique Hotels & Villas",
    Gue_hou: "Guest Houses",
    Bangalo: "Bungalows",
    Home_st: "Home Stay Units",
    Po_ma_un: "Police Marine Unit",
    To_po_un: "Tourist Police Unit",
    Po_li_Sa_u: "Police Life Saving Unit",
    School: "Proximity to School",
    Hospital: "Proximity to Hospital",
    Banks_ATMs: "Availability of Banks/ATMs",
    VTA: "Vocational Training Institute",
    Ag_land: "Agricultural Land",
    Bu_up_a: "Built-Up Area",
    Fo_land: "Forest Land",
    Sandy_a: "Sandy Area",
    Wa_body: "Water Body",
    Wetland: "Wetland",
    Ba_land: "Bare Land",
    Rocky_a: "Rocky Area",
    Wet_Zone: "Wet Zone",
    Dry_Zone: "Dry Zone",
    In_me_Zone: "Intermediate Zone",
    DWC_PA: "Department of Wildlife Conservation Area",
    FD_PA: "Forest Department Protected Area",
    ESA: "Environmentally Sensitive Area",
    Mangrove: "Mangrove Forests",
    Whales: "Whale Sightings",
    Dolphin: "Dolphin Sightings",
    Sharks: "Shark Sightings",
    Sea_tur: "Sea Turtles",
    Coral_r: "Coral Reefs",
    Sea_gra: "Seagrass Beds",
    Bivalve: "Bi-valve",
    Mudflat: "Mudflats",
    Sand_du: "Sand Dunes",
    Lagoon: "Lagoon",
    Estuary: "Estuary",
    Bathing: "Bathing Sites",
    Surfing: "Surfing Areas",
    River_m: "River Mouth",
    Beach_a: "Beach Area",
    Ar_Sites: "Archaeological Sites",
    Solar_I: "Solar Irradiance",
    Wind_po: "Wind Power Potential",
    Rainfall: "Annual Rainfall",
    MR_200m: "Proximity to Main Road (0m - 200m)",
    MR_400m: "Proximity to Main Road (200m - 400m)",
    MR_600m: "Proximity to Main Road (400m - 600m)",
    MR_800m: "Proximity to Main Road (600m - 800m)",
    SR_200m: "Proximity to Secondary Road (0m - 200m)",
    SR_400m: "Proximity to Secondary Road (200m - 400m)",
    SR_600m: "Proximity to Secondary Road (400m - 600m)",
    SR_800m: "Proximity to Secondary Road (600m - 800m)",
    HW_2_5km: "Proximity to Highway (0km - 2.5km)",
    HW_5km: "Proximity to Highway (2.5km - 5km)",
    HW_7_5km: "Proximity to Highway (5km - 7.5km)",
    HW_10km: "Proximity to Highway (7.5km - 10km)",
    RS_2_5km: "Proximity to Railway (0km - 2.5km)",
    RS_5km: "Proximity to Railway (2.5km - 5km)",
    RS_7_5km: "Proximity to Railway (5km - 7.5km)",
    RS_10km: "Proximity to Railway (7.5km - 10km)",
    C_0_200: "Coastal Proximity (0m - 200m)",
    C_200_400: "Coastal Proximity (200m - 400m)",
    C_400_600: "Coastal Proximity (400m - 600m)",
    C_600_800: "Coastal Proximity (600m - 800m)",
    C_800_1000: "Coastal Proximity (800m - 1000m)"
};
